logging:
  LOGGER_NAME: 'root'

load_data:
  SOURCE_BUCKET: "housing-prices-data"

db_config:
  SQLALCHEMY_DATABASE_URI: 'sqlite:///database/usage_log/msia423.db'
  SQLALCHEMY_TRACK_MODIFICATIONS: True
  SQLALCHEMY_ECHO: False  # If true, SQL for queries made will be printed

app_config:
  PORT: 3000
  APP_NAME: "housing-prices"
  HOST: "127.0.0.1"

